### ISSUE TITLE
Support for subdirectories (e.g. site running on devel.domain.com/project1/)

### ISSUE THREAD

**Issue by geraldaistleitner** [cundd/rest#19]
Currently there is no chance to get the extension working if the site is running under a subdirectory. I suggest either using the absRefPrefix or adding a custom setting to maintain it as follows:

\Cundd\Rest\RequestFactory
`123                $pathPrefix = $this->configurationProvider->getSetting('absRefPrefix');`
`124                $uri = substr(str_replace($pathPrefix, "",$_SERVER['REQUEST_URI']), 6);`

The corresponding setting would be
`plugin.tx_rest.settings.absRefPrefix = /project1`

**Comment by geraldaistleitner** [comment]
Unfortunately there is one thing missing that's not covered by your tests.
In ext_localconf.php the eID is only set if the REQUEST_URI param starts with '/rest/' so the extension never gets called for a subdirectory installation.

if (isset($_SERVER['REQUEST_URI']) && substr($_SERVER['REQUEST_URI'], 0, 6) === '/rest/') {
	$_GET['eID'] = 'rest';
}


One possible solution would be the following but this could mess up with RealUrl or something similar if pages are named rest.

if (isset($_SERVER['REQUEST_URI']) && strrpos( $_SERVER['REQUEST_URI'], '/rest/')) {
	$_GET['eID'] = 'rest';
}

**Comment by cundd** [comment]
Oh, yes of course you are right!

I think `strrpos` really is to generally, but I am not sure if we can get access to the parsed TypoScript in `ext_localconf.php`.

**Comment by cundd** [comment]
Is the support for subdirectories mandatory for you?

**Comment by geraldaistleitner** [comment]
TypoScript is not available in `ext_localconf.php`. A possible solution would be, as the extension restler handles this, to do the matching via `.htaccess` with RewriteBase.
Not mandatory, but during development it would be a nice-to-have, as I think many use some sort of development domain and develop in a subdirectory.

**Comment by cundd** [comment]
Or I could introduce an environment variable that defines the part to strip from the request

**Comment by geraldaistleitner** [comment]
As the rest-Extension is normally loaded before the custom extension this will not work without touching your extension and breaking update-compatibility.

**Comment by cundd** [comment]
I thought about a environment variable like TYPO3_CONTEXT which can be set in .htaccess or alike

**Comment by geraldaistleitner** [comment]
That would be possible, but then it should be removed from TypoScript as this would be redundant.

**Comment by cundd** [comment]
You mean the `$pathPrefix = $this->configurationProvider->getSetting('absRefPrefix');` part?

**Comment by geraldaistleitner** [comment]
Yes. We would have to specify the Prefix then twice...

**Comment by cundd** [comment]
I added the environment variable TYPO3_REST_REQUEST_BASE_PATH. 

As an example it can be set in the `.htaccess`file with
```
RewriteRule .? - [E=TYPO3_REST_REQUEST_BASE_PATH:/my-sub-directory]
```

I let the `absRefPrefix` in the Request Factory as a fallback, but it may doesn't make sense. I think I will remove it.

**Comment by geraldaistleitner** [comment]
Works like a breeze now. Thank you. :)

**Comment by cundd** [comment]
:+1: I'm gonna merge it into master ASAP
