### ISSUE TITLE
<link> in TCA type 'text'

### ISSUE THREAD

**Issue by geraldaistleitner** [cundd/rest#22]
link tags are not parsed to a-tags

**Comment by cundd** [comment]
The reason for this is, that the Virtual Objects simply output the data from the table without any processing.

**Comment by geraldaistleitner** [comment]
Do you have plans to extend Virtual Objects to handle this?

**Comment by cundd** [comment]
Not at the moment. Do you know if the TYPO3 core provides "Extbase-enabled" access to the pages and content?

**Comment by geraldaistleitner** [comment]
Unfortunately I think there is no simple solution to this. I just disabled ts_links in TCA Configuration, so the link won't get transformed when stored in database.

**Comment by cundd** [comment]
Did you speak about a custom extension or at least an Extbase model? Maybe I misunderstood you.

**Comment by geraldaistleitner** [comment]
I have an extension with an extbase model. I access the model with your rest extension.

**Comment by cundd** [comment]
Then you could transform the <link> elements in the method [jsonSerialize()](http://php.net/manual/en/jsonserializable.jsonserialize.php) of your domain model
