### ISSUE TITLE
Persistence Mapping is not respected

### ISSUE THREAD

**Issue by doerler** [cundd/rest#24]
If I've a Model with persistence mapping

```
plugin.tx_myext {
	persistence {
		classes {
			Vendor\MyExt\Domain\Model\FrontendUser {
				mapping {
					tableName = fe_users
					recordType = Vendor\MyExt\Domain\Model\FrontendUser
					columns {
						felogin_forgotHash.mapOnProperty = feloginForgotHash
					}
				}
			}
		}
	}
}
```

the extension searches for a table called `tx_myext_domain_model_frontenduser`.

**Comment by cundd** [comment]
Do you have a normal frontend or backend plugin too? Or do you only want to communicate through REST?

**Comment by doerler** [comment]
We have a normal FE plugin too.

**Comment by cundd** [comment]
And there everything works as expected?

**Comment by doerler** [comment]
Yes indeed ;)

**Comment by cundd** [comment]
The REST extension only makes use of Extbase. Actually the mapping should work if Extbase can read it correctly.

**Comment by cundd** [comment]
What TYPO3 version are you running?

**Comment by doerler** [comment]
I'm running the latest stable 7 LTS (7.6.9)

**Comment by cundd** [comment]
Did you open source your extension, so that I could have a deeper look?

**Comment by doerler** [comment]
Regrettably, we are unable to publish this extension under Open Source.

**Comment by doerler** [comment]
But since you say it should work, I trust you and will have a deeper look into it.

**Comment by cundd** [comment]
Another user also mapped the frontend user: https://gitter.im/cundd/rest?at=56781849f31bbe91555b86ad

**Comment by doerler** [comment]
OK, it looks like it was a caching problem :/ Sorry for the noise!

**Comment by cundd** [comment]
No problem
