### ISSUE TITLE
[BUG] FrontendUserAuthentication::fetchSessionData()

### ISSUE THREAD

**Issue by ogrosko** [cundd/rest#35]
I'm using basic authentication. when user is not authenticated or authentication is wrong I get following error

> Uncaught TYPO3 Exception
Call to undefined method TYPO3\CMS\Frontend\Authentication\FrontendUserAuthentication::fetchSessionData() 

>Error thrown in file
/Users/ondro/Sites/tourismustage.local/web/typo3conf/ext/rest/Classes/Cundd/Rest/SessionManager.php in line 33.

I think problem is caused by [this change](https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.6/Breaking-70316-AbstractUserAuthenticationPropertiesAndMethodsDroppedAndChanged.html)

Temporary fix: remove line 33 `$GLOBALS['TSFE']->fe_user->fetchSessionData();` from `rest/Classes/Cundd/Rest/SessionManager.php`

Typo3 v8.7.1, rest v2.2.2

**Comment by cundd** [comment]
Thank you for the detailed report and your analysis!

Could you please test the fix and give me feedback?

**Comment by ogrosko** [comment]
Your fix is made against to master i guess.
But with the version 2.2.2 there is no method `SessionManager::getFrontendUser()`

**Comment by cundd** [comment]
Sorry. I just updated the master's README to make it more clear.

For future bugfixes for 2.2.x the branch v2 exists. Could you checkout this one?

**Comment by ogrosko** [comment]
Works fine
