### ISSUE TITLE
[BUG] double Content-Type

### ISSUE THREAD

**Issue by hansup** [cundd/rest#36]
In my custom rest TYPO3 extension, I use the TS setting:
plugin.tx_rest.settings. responseHeaders.Content-Type = application/json

As a result of the this, my results get the right header, that is: 
Content-Type: application/json;

But, because of this, the /rest/auth/login requests get the header:
Content-Type: application/json, application/json;

... which is throwing an error with some strict REST clients.
Is it an idea to remove line 122 in the file "ResponseFactory.php":
$response = $response->withHeader(Header::CONTENT_TYPE, 'application/json');

...or make it conditional?

**Comment by cundd** [comment]
Which version are you running? I guess you are on 3.0?

Is the Content-Type correct (aside from the custom extension's response)?

**Comment by hansup** [comment]
3.0.0-rc2
When I remove the TS setting in the custom extension, then the /rest/auth/login requests get the correct header:
Content-Type: application/json;

**Comment by cundd** [comment]
So the problem may lay a bit deeper: If one uses a custom extension, and returns a raw array as a result, the Content-Type is not correctly set.

If the Content-Type would be appropriately set for custom Handler responses, your problem would be solved, right?

**Comment by hansup** [comment]
Probably :-)

**Comment by cundd** [comment]
Do you return a raw array like in the following code?

```php
 $router->add(
            Route::get(
                $request->getResourceType(),
                function (RestRequestInterface $request) {
                    return array(
                        'path'         => $request->getPath(),
                        'uri'          => (string)$request->getUri(),
                        'resourceType' => (string)$request->getResourceType(),
                    );
                }
            )
        );
```

**Comment by hansup** [comment]
No, this is my route:
<div class="highlight highlight-text-html-php">
<pre>
$router->add(
    Route::get(
        '/vendor-extension-product/barcode/{slug}',
        function (RestRequestInterface $request, $slug) {
            $arguments = [
                'barcode' => $slug,
            ];
            return $this->helper->callExtbasePlugin(
                'plugin',
                'vendor',
                'extension',
                'Product',
                'barcode',
                $arguments
            );
        }
    )
);
</pre></div>

**Comment by cundd** [comment]
I made a change to the Custom Rest extension. After creating a Response form the Extbase result I manually add the Content-Type header to the Response. So the header is added at the right position in the program flow.

https://github.com/cundd/custom_rest/blob/93e3a50896afa2f15c60dc81f5a943ffc70cf694/Classes/Rest/Helper.php#L64

The TypoScript `plugin.tx_rest.settings.responseHeaders` was meant for adding headers which should be added to every response.

**Comment by hansup** [comment]
I catch your drift, but I get a 500 internal server error with those lines added to my Helper.php. I'm looking into this later. Have to go now. Thank you for your help so far.

**Comment by cundd** [comment]
I'll close this issue.

Don't hesitate to ask on https://gitter.im/cundd/rest, if you have a question.
