### ISSUE TITLE
Query Parameters

### ISSUE THREAD

**Issue by joaomvfsantos** [cundd/rest#40]
Hello, do you support query parameters? If yes, how should one define it in the routes?

**Comment by cundd** [comment]
For the routing, only the path (i.e. [PSR 7 Uri](http://www.php-fig.org/psr/psr-7/#35-psrhttpmessageuriinterface) `getPath()`) is matched. 

Query parameters have to be handled by the custom handler.

**Comment by joaomvfsantos** [comment]
Thank you for your response. You gave me a few lights on how to proceed. Feel free to close this.
