### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by JarvisH** [cundd/rest#42]
Hi!

First off: Thank you for a great extension!

Would it be possible to create custom caching durations on a per request basis?

I had a project where php/db operations for certain requests were somewhat intensive but those requests could then be cached for a long time (several days), as caches were then invalidated using flushByTag when content changed.

Certain other requests however could not be cached for a long time as invalidating their caches proved difficult or the content belonging to those requests changed so often that a cache duration set to a few hours was best.

As far as I can tell only the ts-setting "cacheLifeTime" can be used to influence caching durations, or am I missing something?

**Comment by cundd** [comment]
Hy!

You are right: currently there is only the "global" `cacheLifeTime` TypoScript setting. In a custom extension, the TYPO3's caching framework could be utilised directly.

Theoretically the configuration of a path could accept a `cacheLifeTime` parameter too - which could then be used to determine the caching.

**Comment by cundd** [comment]
A thing I totally forgot about is the possibility to use a custom cache class (see https://github.com/cundd/rest/commit/715925968824194cb4b9ca1aacc2c0dc7e1f2d9c)

**Comment by cundd** [comment]
Since 6e6433cf0f5f0f6d1d3e1c3e85cacdfe7e9893d1 it is possible to also define the `cacheLifeTime` in the path configuration:

```TypoScript

plugin.tx_rest.settings {
    paths {
        virtual_object-content {
            path = virtual_object-content
            read = deny
            write = deny
            cacheLifeTime = 100000
        }
    }
}
```

Could you please test it? :)

**Comment by JarvisH** [comment]
Thank you for your feedback. I ended up using a modified version of the rest caching mechanism to enable auth checks in the route handler itself. Obviously auth checks would be better implemented as middleware, but I wasn't quite sure how to do that with the existing setup.

Anyway, my problem is solved so I will close this issue.

Thanks again!
