### ISSUE TITLE
cundd in TYPO3 9

### ISSUE THREAD

**Issue by rorentz** [cundd/rest#48]
Is that extension compatible with TYPO3 9 or has TYPO3 9 an out of the box solution to generate routes ? 

Thanks.

**Comment by cundd** [comment]
I can't answer your questions yet. 

Regarding the my REST extension: Give it a try :)

**Comment by cundd** [comment]
A fully functional version with TYPO3 9 support is currently in the making

**Comment by rorentz** [comment]
That is Great. Especially defining a Route that maps to an extbase PluginAction is very helpful.

**Comment by cundd** [comment]
I add support for TYPO3 9 in tag [3.4.0-beta2](https://github.com/cundd/rest/tree/3.4.0-beta2).

I hoped for some feedback from the community, but didn't get a response so far.

**Comment by rorentz** [comment]
Give me one week and i would like to give a Feedback! Have you Seen the Problem with the LocalizationUtility i posted in the other issue?

**Comment by cundd** [comment]
Great!

Yes I've seen the other issue. I already created a branch, but I need to add some tests to verify the correct behavior.

**Comment by cundd** [comment]
Fixed in 3.5.0

**Comment by rorentz** [comment]
@cundd : I want to say sorry for not keeping my promise to recheck. I had some bigger troubles last year. Sorry :-(

**Comment by cundd** [comment]
Absolutely no problem.
