### ISSUE TITLE
HMAC or JWT Authentification

### ISSUE THREAD

**Issue by martinavk** [cundd/rest#49]
Hi, 
I was wondering if it is possible that a HMAC or a JWT authentification will be included into this extension? The Base Auth (or the Login request) is not strong enough for our purpose. 

Or what would I need to do to implement it?

Thank you!

**Comment by cundd** [comment]
There are no plans to provide other authentication methods in the near future. The extension should be self-contained without external dependencies. I'm an absolute noob when it comes to all those different authentication methods. So I hesitate to implement them :)

But the extension allows you to define a custom set of authentication providers. You can override those in TypoScript with `plugin.tx_rest.settings.authenticationProvider`.
