### ISSUE TITLE
TCA Migrations Typo3 8.7.22

### ISSUE THREAD

**Issue by zolthan** [cundd/rest#50]
Hi,

I just installed your extension and ran the TCA migrations option from the install tool. There are some TCA definitions which have to be revised for the current Typo3 8 version.

TCA migrations need to be applied

Check the following list and apply needed changes.

The 4th parameter 'specConf' of the field 'showitem' with fieldName = 'tx_rest_apikey' has been migrated, from TCA table "fe_users['types']['0']['showitem']"to "fe_users['types']['0']['columnsOverrides']['tx_rest_apikey']['defaultExtras']".

The 4th parameter 'specConf' of the field 'showitem' with fieldName = 'tx_rest_apikey' has been migrated, from TCA table "fe_users['types']['Tx_Extbase_Domain_Model_FrontendUser']['showitem']"to "fe_users['types']['Tx_Extbase_Domain_Model_FrontendUser']['columnsOverrides']['tx_rest_apikey']['defaultExtras']".

Best
Sebastian

**Comment by cundd** [comment]
Hy Sebastian

Thank you for the hint. I looked into this a few weeks ago. In the extension TYPO3's API methods are used (see https://github.com/cundd/rest/blob/v3/Configuration/TCA/Overrides/fe_users.php#L19-L28). The TCA is not customised manually - so this should be "fixed" as soon as the methods in Core are updated.

**Comment by varioous** [comment]
+1 ... not important but should be fixed in next version.
