### ISSUE TITLE
Allow cacheLifeTime to be overwritten for given path level

### ISSUE THREAD

**Issue by presstype** [cundd/rest#51]
Hello, 
once again thanks for your work and this extension. 

I`m trying to overwrite global cacheLifeTime value on the object path level, it looks like we are not able to store this value without given resourceType in function buildCache.
https://github.com/cundd/rest/blob/e683520a51457f4fc37899a490525b1307a0357a/Classes/Cache/CacheFactory.php#L15-L24

I wrote patch for that which works for me in our project, unfortunately its hard for me to say if thats the final and proper way to do it.
[CacheLifeTime_patch.txt](https://github.com/cundd/rest/files/2833109/CacheLifeTime_patch.txt)

Best regards!

**Comment by cundd** [comment]
Hello! 

Should be fixed in 840a16447d93cf7e295583f5fa2e8e71089ec5c2

**Comment by presstype** [comment]
Hi Daniel! Thank you very much - it worked very well for us.

**Comment by cundd** [comment]
Great! Thank you for your feedback
