### ISSUE TITLE
typo3scan against TYPO3 9

### ISSUE THREAD

**Issue by jacobsenj** [cundd/rest#52]
Here's the result scanning ext:rest with typo3scan (https://github.com/Tuurlijk/typo3scan).

Found **13** matches in **5.70s** when
checking for changes and deprecations in **TYPO3 9**

 strong |  weak |  BREAKING |  DEPRECATION | 
 --- |  --- |  --- |  --- | 
 38.5% (5) |  61.5% (8) |  38.5% (5) |  61.5% (8) | 
### Access to global array "TYPO3_DB" *(strong)*
26 `return new V7Backend($GLOBALS['TYPO3_DB']);`

- [Breaking: #80929 - TYPO3_DB moved to extension](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-80929-TYPO3_DBMovedToExtension.html)

### Access to global array "TYPO3_DB" *(strong)*
35 `if (!isset($GLOBALS['TYPO3_DB'])) {`

- [Breaking: #80929 - TYPO3_DB moved to extension](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-80929-TYPO3_DBMovedToExtension.html)

### Access to global array "TYPO3_DB" *(strong)*
39 `$database = $GLOBALS['TYPO3_DB'];`

- [Breaking: #80929 - TYPO3_DB moved to extension](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-80929-TYPO3_DBMovedToExtension.html)

### Usage of class "TYPO3\CMS\Core\Database\DatabaseConnection" *(strong)*
41 `return is_object($database) && $database instanceof \TYPO3\CMS\Core\Database\DatabaseConnection;`

- [Breaking: #80929 - TYPO3_DB moved to extension](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-80929-TYPO3_DBMovedToExtension.html)

### Usage of class "TYPO3\CMS\Core\Database\DatabaseConnection" *(strong)*
28 `public function __construct(DatabaseConnection $connection)`

- [Breaking: #80929 - TYPO3_DB moved to extension](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-80929-TYPO3_DBMovedToExtension.html)

### Access to array key "extConf" *(weak)*
307 `&& isset($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'])`

- [Deprecation: #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html)

### Access to array key "extConf" *(weak)*
308 `&& isset($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['rest'])`

- [Deprecation: #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html)

### Access to array key "extConf" *(weak)*
310 `$configuration = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['rest']);`

- [Deprecation: #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html)

### Fetch of property "config" *(weak)*
151 `$frontendController->config['config']['sys_language_uid'] = $requestedLanguageUid;`

- [Deprecation: #84307 - Protected methods and properties in NewContentElementController](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.2/Deprecation-84307-ProtectedMethodsAndPropertiesInNewContentElementController.html)

### Call to method "getIdentityProperties()" *(weak)*
274 `$identityProperties = $classSchema->getIdentityProperties();`

- [Deprecation: #57594 - Optimize extbase ReflectionService Cache handling](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-57594-OptimizeReflectionServiceCacheHandling.html)

### Access to array key "extConf" *(weak)*
22 `&& isset($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'])`

- [Deprecation: #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html)

### Access to array key "extConf" *(weak)*
23 `&& isset($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['rest'])`

- [Deprecation: #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html)

### Access to array key "extConf" *(weak)*
25 `$configuration = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['rest']);`

- [Deprecation: #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html)

**Comment by cundd** [comment]
Thank you. That's interesting.

The hardest part may be to replace `$frontendController->config['config']['sys_language_uid'] = $requestedLanguageUid;`. The rest should be a matter of replacing `$GLOBALS['TYPO3_CONF_VARS']` and to remove the non-Doctrine backend for Virtual Objects.

What do you think: Should I drop support for TYPO3 7?

**Comment by jacobsenj** [comment]
I would suggest so, yes. Maybe you could also start a version 4. branch for TYPO3 9 only and continue support for TYPO3 8 in the 3. branch. But thats fully up to you.

**Comment by cundd** [comment]
v4 is already there :) 

I cleaned up the Data Provider a lot and made some changes to use the Extension for stuff beside TYPO3

**Comment by cundd** [comment]
Hmm `ExtensionConfiguration` is only available in TYPO3 9 - so removing calls to `$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['rest']` will break 8 LTS Support too.

**Comment by jacobsenj** [comment]
Yep you're right. Changing this would be possible on a TYPO3 9.5 Version only.

**Comment by cundd** [comment]
I think I'll change that in the next version when TYPO3 10 LTS is out and close the ticket for now.

Thank you for bringing this up
