### ISSUE TITLE
is querying for values possible?

### ISSUE THREAD

**Issue by MDSLKTR** [cundd/rest#53]
Hey thanks for the very useful extension. I like it a lot and would like to create a page renderer for a SPA. The question to make this efficient would be if on the route ```/rest/virtual_object-content``` something like ```?pageIdentifier=5``` would be possible? Or even ```/rest/virtual_object-page/5/virtual_object-content``` would be a nice shorthand. This would allow quick fetching of the page and the page content while not having the overhead of fetching all page content.

Regards,
Simon

**Comment by cundd** [comment]
Hi Simon! Thank you for your feedback!

At the moment filters are not implemented. Your second approach would work for Extbase models (e.g. `http://localhost/rest/georg_ringer-news-news/1/falMedia`) but unfortunately not for `VirtualObject`s.

**Comment by MDSLKTR** [comment]
Hey thanks for the quick reply. This is unfortunate but maybe this can be solved using a custom route provider. I'll have a look.
