### ISSUE TITLE
Additional Header missing if isUnauthorized or isDenied

### ISSUE THREAD

**Issue by thoho-mpa** [cundd/rest#54]
if an Request is Unauthorized or Denied Additional Headers (e.g. CORS Headers) are missing.
I fixed it local in my installation. 

I Attached a Patch file.
[typo3_rest_addAdditionalHeaders_patch.zip](https://github.com/cundd/rest/files/2904663/typo3_rest_addAdditionalHeaders_patch.zip)

**Comment by cundd** [comment]
Hy!

Thank you for the notice. I also ran into this and fixed it in [v4](https://github.com/cundd/rest/blob/v4/Classes/Dispatcher.php#L101). Could you have a look at the upcoming version? It also has a much cleaner interface for the DataProviders (if that is of interest for you).

**Comment by cundd** [comment]
Fixed in ba3f86ccd977a4364c342bb6bc3208c7d9985568
