### ISSUE TITLE
Documentation Page is not available

### ISSUE THREAD

**Issue by develth** [cundd/rest#55]
Hi, 

the page ```https://rest.cundd.net``` is not available. It redirects to ```https://rest.corn.rest/```which can´t be resolved.

Regards,
Thomas

**Comment by cundd** [comment]
Hi Thomas

Thank you for the information - although I can't reproduce the problem on any of our servers. Could this be a problem with your firewall?

To check out the docs in your case you can have a look into https://github.com/cundd/rest/tree/v3/Documentation. There are the Markdown files that are served by the website.

Best regards

Daniel

**Comment by develth** [comment]
Hi Daniel,

thanks for the fast feedback. Checked it on an external server and definitely local issue.

Thanks & Best regards
Thomas
