### ISSUE TITLE
Adapt definition of fe_user.tx_rest_apikey

### ISSUE THREAD

**Issue by robert-heinig** [cundd/rest#62]
With this extensions installed no new fe_users can be created without explicitly setting a value for tx_rest_apikey, because this column is defined as
`tx_rest_apikey tinytext NOT NULL`
in ext_tables.sql.

Since TEXT type fields do not have default values, "NOT NULL" should be removed from the definition.
Setting an empty string instead of allowing NULL does not seems to have any advantage when not using this field.

**Comment by cundd** [comment]
Thanks for the report. I removed `NOT NULL` from ext_tables
