### ISSUE TITLE
Compatibility with TYPO3 v10

### ISSUE THREAD

**Issue by r3h6** [cundd/rest#65]
Do you intend to make this extension compatible with TYPO3 v10?

**Comment by cundd** [comment]
That's actually linked to #61. I hope that a middleware based implementation will bring a major step forward to v10 compatibility.

**Comment by cundd** [comment]
If there is the demand for compatibility with v10 from a company, a sponsoring could increase the motivation to invest time into development. ;)

**Comment by varioous** [comment]
+1

**Comment by cundd** [comment]
Fixed in https://github.com/cundd/rest/tree/v5

The update took quite some effort. So sponsoring is more then welcome ;)
