### ISSUE TITLE
Cannot instantiate ObjectManagerInterface

### ISSUE THREAD

**Issue by gotypo** [cundd/rest#69]
Hey Daniel ,

we are using your rest extension version 5.0.0 on TYPO3 10 with PHP 7.4. 

We extend our own class "DataProvider" with "\Cundd\Rest\DataProvider\DataProvider" and this causes the following Error

"error": "API Error #0 :Cannot instantiate interface Cundd\\Rest\\ObjectManagerInterface",

We also added the Extension\Configuration\Services.yaml in our extension with the following config:

-----------------------------------
```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Namespace\Extension\:
    resource: '../Classes/*'

  Cunnd\Rest\DataProvider\DataProvider: '@Namespace\Extension\Rest\DataProvider'

  Cundd\Rest\ObjectManagerInterface:
    public: true

  Cundd\Rest\DataProvider\ExtractorInterface:
    public: true

  Cundd\Rest\DataProvider\IdentityProviderInterface:
    public: true

```
-----------------------------------

so the ObjectManagerInterface is set to public. 

Do you have any advice where to look at or did we something wrong with the configuration?

Thanks a lot.

Cheers
Christian

**Comment by cundd** [comment]
Hi Christian

Do you get the stack trace if you set the `devIPmask` to '*'?

As a possible workaround you could try to add a definition for `Cundd\Rest\ObjectManagerInterface` in [ext_localconf.php](https://github.com/cundd/rest/blob/737299005863ff2a18694f0878a6d3664cc565bf/ext_localconf.php#L42)

**Comment by gotypo** [comment]
Hey Daniel,

we figgured out that this bug was caused by the PHP Version 7.4 and symfony. The dependecy injections got handled in the wrong way. Just to let you know in case that someone comes up with the same issue one time.

Thanks a lot
Christian

**Comment by cundd** [comment]
Hi Christian

Thank you for the update on this!

**Comment by nabossha** [comment]
@gotypo i am experiencing the same problem, migrating from V4 to V5 i try using my own dataprovider which seems to be ignored. clearing all caches / temp-folders did not help anything. 
maybe you can give me a hint on what you had to fix on DI?
