### ISSUE TITLE
Version development

### ISSUE THREAD

**Issue by waltermulder** [cundd/rest#72]
The most recent version is updated last year (beta) and not suitable for typo3 v11. Is the REST API  stilll maintained and are there plans for making the REST API suitable for TYPO3 version 11 ?

**Comment by cundd** [comment]
The extension is one of my side projects. Featurewise the extension is relatively complete (beside the bigger additions like Headless CMS features).

Regarding TYPO3 v11 support: I currently don't have the need to support v11, so it's not on my priority list. But I think others did look into this. (@jacobsenj do you think there is a lot to do, to make it v11 ready?)

**Comment by jacobsenj** [comment]
I've tried to start with the update, but have not got it working yet.

**Comment by fazzyx** [comment]
I would recommend [rector](https://github.com/sabbelasichon/typo3-rector) to ensure compatibility with TYPO3 11

**Comment by cundd** [comment]
> I would recommend [rector](https://github.com/sabbelasichon/typo3-rector) to ensure compatibility with TYPO3 11

Thank you. That looks interesting, although I guess, that the major work is in the Rest Bootstrap classes. Not sure how much the tool can help there.

**Comment by cundd** [comment]
Update: I didn't find time to look into this yet, and I'm not sure if I'll find time in the near future. But I am happy to help if somebody has a more specific question.

**Comment by cundd** [comment]
I just pushed an alpha version for TYPO3 v11 support

https://github.com/cundd/rest/tree/feature/typo3-11

I removed the support to invoke Extbase controller actions from the `EXT:custom_rest` example.
