### ISSUE TITLE
Typo3 version 11 support

### ISSUE THREAD

**Issue by sapfeer0k** [cundd/rest#73]
Hi @cundd ,

Thanks for the amazing extension. I saw you've added the support for v11 in the feature branch. Could you share your plans about including those changes in the next release? When do you plan to do it? May be I help you to make the release happen faster?

**Comment by cundd** [comment]
> May be I help you to make the release happen faster?

It would already be a big help if you could test the branch and give me feedback.

I'd like to publish a new release with v11 support as soon as I got feedback that it's working properly.

**Comment by sapfeer0k** [comment]
Hi @cundd ,

I can confirm that the API works with typo3 v11 for us.

**Comment by cundd** [comment]
Thank you for your feedback.

I decided to merge the branch into v5 and tag [release 5.1.0](https://github.com/cundd/rest/releases/tag/5.1.0)
